#!/usr/bin/env sh
# Generates libraries/authz/fga/model.fga.yaml from model.fga + tests.fga.yaml.
# Run this whenever either source file changes.
set -eu

cd "$(dirname "$0")/../libraries/authz/fga"

{
  printf '# Generated by scripts/gen-test-yaml.sh — do not edit by hand.\n'
  printf '# Source files: libraries/authz/fga/model.fga + libraries/authz/fga/tests.fga.yaml.\n'
  printf 'model: |\n'
  sed 's/^/  /' model.fga
  printf '\n'
  cat tests.fga.yaml
} > model.fga.yaml
