[package]
name = "authz"
version = "0.1.0"
edition = "2021"

[dependencies]
library-core = { path = "../library-core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
